### ISSUE TITLE
Purchasing Equipment/Stats has impossibly high gas cost (and fails)

### ISSUE THREAD

**Issue by sbash** [BattleDrome/Core#6]
Whether +1 or mutliples it gives me the same error:

![image](https://user-images.githubusercontent.com/18412275/38004693-6addf34c-320b-11e8-8d92-ee38a4aa7212.png)

**Comment by pmumby** [comment]
This one may be related to outdated browser cache of some javascripts, or other artifacts.

Attempted to re-create on a clean client, and was unable to re-create.

Will investigate further.
